### ISSUE TITLE
Server Worldgen Issue

### ISSUE THREAD

**Issue by Doctor-nova** [ultixon/OccultCraft#18]
On version 5.7
After agreeing to the EULA, I used run.bat. Worldgen would hang on 97% constantly.

**Comment by Doctor-nova** [comment]
Some consistent errors I'm finding during the worldgen process:
[Worker-Main-1/ERROR] [minecraft/HangingEntity]: Hanging entity at invalid position: BlockPos{x=-238, y=-12, z=112}

[15:43:51] [Server thread/ERROR] [minecraft/BlockableEventLoop]: Error executing task on Chunk source main thread executor for minecraft:overworld
java.util.concurrent.CompletionException: java.lang.NullPointerException: Registry Object not present: apotheosis:anvil
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:535) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:classloading}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:543) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:classloading}
        at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:267) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:751) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_129940_(MinecraftServer.java:447) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:302) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:165) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.NullPointerException: Registry Object not present: apotheosis:anvil
        at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {re:mixin}
        at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19.2-43.2.8-universal.jar%23458!/:?] {re:mixin,re:classloading}
        at shadows.apotheosis.ench.anvil.AnvilTile.<init>(AnvilTile.java:24) ~[Apotheosis-1.19.2-6.1.5.jar%23282!/:6.1.5] {re:classloading}
        at fuzs.easyanvils.integration.apotheosis.ApothAnvilBlockEntity.<init>(ApothAnvilBlockEntity.java:38) ~[EasyAnvils-v4.0.11-1.19.2-Forge.jar%23324!/:4.0.11] {re:classloading}
        at fuzs.easyanvils.init.ForgeModRegistry$1.create(ForgeModRegistry.java:27) ~[EasyAnvils-v4.0.11-1.19.2-Forge.jar%23324!/:4.0.11] {re:classloading}
        at net.minecraft.world.level.block.entity.BlockEntityType.m_155264_(BlockEntityType.java:86) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:BlockEntityTypeAccessor,pl:mixin:APP:davespotioneering.mixins.json:BlockEntityTypeAcces,pl:mixin:APP:vampirism.mixins.json:TileEntityTypeAccessor,pl:mixin:A}
        at net.minecraft.world.level.block.AnvilBlock.m_142194_(AnvilBlock.java:561) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,re:classloading,pl:mixin:APP:easyanvils.common.mixins.json:AnvilBlockMixin,pl:mixin:APP:placebo.mixins.json:AnvilBlockMixin,pl:mixin:A}
        at net.minecraft.world.level.chunk.LevelChunk.m_62870_(LevelChunk.java:517) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LevelChunkMixin,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin,pl:mixin:APP:corgilib.mixins.json:chunk.MixinLevelChunk,pl:mixin:APP:lootr.mixins.json:MixinLevelChunk,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkAccessAccess,pl:mixin:A}
        at net.minecraft.world.level.chunk.LevelChunk.m_5685_(LevelChunk.java:298) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LevelChunkMixin,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin,pl:mixin:APP:corgilib.mixins.json:chunk.MixinLevelChunk,pl:mixin:APP:lootr.mixins.json:MixinLevelChunk,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkAccessAccess,pl:mixin:A}
        at net.minecraft.world.level.chunk.LevelChunk.m_7702_(LevelChunk.java:285) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LevelChunkMixin,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin,pl:mixin:APP:corgilib.mixins.json:chunk.MixinLevelChunk,pl:mixin:APP:lootr.mixins.json:MixinLevelChunk,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkAccessAccess,pl:mixin:A}
        at net.minecraft.world.level.chunk.LevelChunk.m_62812_(LevelChunk.java:504) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LevelChunkMixin,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin,pl:mixin:APP:corgilib.mixins.json:chunk.MixinLevelChunk,pl:mixin:APP:lootr.mixins.json:MixinLevelChunk,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkAccessAccess,pl:mixin:A}
        at net.minecraft.server.level.ChunkMap.m_214959_(ChunkMap.java:724) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
        at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
        at net.minecraft.server.level.ChunkMap.m_214929_(ChunkMap.java:723) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
        ... 16 more
[15:43:51] [Server thread/ERROR] [minecraft/BlockableEventLoop]: Error executing task on Chunk source main thread executor for minecraft:overworld
java.util.concurrent.CompletionException: java.lang.NullPointerException: Registry Object not present: apotheosis:anvil
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:535) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:classloading}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:543) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:classloading}
        at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:267) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:751) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_129940_(MinecraftServer.java:447) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:302) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:165) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.NullPointerException: Registry Object not present: apotheosis:anvil
        at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {re:mixin}
        at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19.2-43.2.8-universal.jar%23458!/:?] {re:mixin,re:classloading}
        at shadows.apotheosis.ench.anvil.AnvilTile.<init>(AnvilTile.java:24) ~[Apotheosis-1.19.2-6.1.5.jar%23282!/:6.1.5] {re:classloading}
        at fuzs.easyanvils.integration.apotheosis.ApothAnvilBlockEntity.<init>(ApothAnvilBlockEntity.java:38) ~[EasyAnvils-v4.0.11-1.19.2-Forge.jar%23324!/:4.0.11] {re:classloading}
        at fuzs.easyanvils.init.ForgeModRegistry$1.create(ForgeModRegistry.java:27) ~[EasyAnvils-v4.0.11-1.19.2-Forge.jar%23324!/:4.0.11] {re:classloading}
        at net.minecraft.world.level.block.entity.BlockEntityType.m_155264_(BlockEntityType.java:86) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:BlockEntityTypeAccessor,pl:mixin:APP:davespotioneering.mixins.json:BlockEntityTypeAcces,pl:mixin:APP:vampirism.mixins.json:TileEntityTypeAccessor,pl:mixin:A}
        at net.minecraft.world.level.block.AnvilBlock.m_142194_(AnvilBlock.java:561) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,re:classloading,pl:mixin:APP:easyanvils.common.mixins.json:AnvilBlockMixin,pl:mixin:APP:placebo.mixins.json:AnvilBlockMixin,pl:mixin:A}
        at net.minecraft.world.level.chunk.LevelChunk.m_62870_(LevelChunk.java:517) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LevelChunkMixin,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin,pl:mixin:APP:corgilib.mixins.json:chunk.MixinLevelChunk,pl:mixin:APP:lootr.mixins.json:MixinLevelChunk,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkAccessAccess,pl:mixin:A}
        at net.minecraft.world.level.chunk.LevelChunk.m_5685_(LevelChunk.java:298) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LevelChunkMixin,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin,pl:mixin:APP:corgilib.mixins.json:chunk.MixinLevelChunk,pl:mixin:APP:lootr.mixins.json:MixinLevelChunk,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkAccessAccess,pl:mixin:A}
        at net.minecraft.world.level.chunk.LevelChunk.m_7702_(LevelChunk.java:285) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LevelChunkMixin,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin,pl:mixin:APP:corgilib.mixins.json:chunk.MixinLevelChunk,pl:mixin:APP:lootr.mixins.json:MixinLevelChunk,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkAccessAccess,pl:mixin:A}
        at net.minecraft.world.level.chunk.LevelChunk.m_62812_(LevelChunk.java:504) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LevelChunkMixin,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin,pl:mixin:APP:corgilib.mixins.json:chunk.MixinLevelChunk,pl:mixin:APP:lootr.mixins.json:MixinLevelChunk,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkAccessAccess,pl:mixin:A}
        at net.minecraft.server.level.ChunkMap.m_214959_(ChunkMap.java:724) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
        at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
        at net.minecraft.server.level.ChunkMap.m_214929_(ChunkMap.java:723) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
        ... 16 more

**Comment by Doctor-nova** [comment]
Figured it out, bad apotheosis config on my end.
